[tool.poetry]
name = "vrest"
version = "0.2.0"
description = ""
authors = ["VortexRoot"]
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.12,>=3.9"
requests = "^2.31.0"
websockets = "^11.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
